question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},

    {"text": "Bananas are berries.", "answer": "True"},
    {"text": "Strawberries are berries.", "answer": "False"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "Bats are blind.", "answer": "False"},
    {"text": "A group of flamingos is called a flamboyance.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "Koalas sleep up to 20 hours a day.", "answer": "True"},
    {"text": "A snail can sleep for three years.", "answer": "True"},
    {"text": "Cows have four stomachs.", "answer": "False"},
    {"text": "The fingerprints of a koala are nearly identical to humans.", "answer": "True"},
    {"text": "An ostrich's eye is bigger than its brain.", "answer": "True"},

    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Water boils at 100°C everywhere on Earth.", "answer": "False"},
    {"text": "The Earth is closer to the Sun in January than in July.", "answer": "True"},
    {"text": "Sound travels faster in water than in air.", "answer": "True"},
    {"text": "Humans can distinguish over one trillion smells.", "answer": "True"},
    {"text": "Goldfish only have a memory of three seconds.", "answer": "False"},
    {"text": "Hot water freezes faster than cold water under certain conditions.", "answer": "True"},
    {"text": "Diamonds are made entirely of carbon.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},

    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "Your skin is the largest organ in the human body.", "answer": "True"},
    {"text": "Adults have fewer bones than babies.", "answer": "True"},
    {"text": "Humans share about 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The human heart is on the left side of the chest.", "answer": "False"},
    {"text": "The strongest muscle in the human body is the tongue.", "answer": "False"},
    {"text": "The average person produces enough saliva in a lifetime to fill two swimming pools.", "answer": "True"},

    {"text": "The Eiffel Tower can grow taller in summer.", "answer": "True"},
    {"text": "Australia is wider than the Moon.", "answer": "True"},
    {"text": "Russia spans eleven time zones.", "answer": "True"},
    {"text": "The Sahara Desert is the largest desert on Earth.", "answer": "False"},
    {"text": "Mount Everest is the tallest mountain above sea level.", "answer": "True"},
    {"text": "Canada has more lakes than the rest of the world combined.", "answer": "True"},

    {"text": "Venus is the hottest planet in our solar system.", "answer": "True"},
    {"text": "Mars has two moons.", "answer": "True"},
    {"text": "The Sun is a planet.", "answer": "False"},
    {"text": "A day on Venus is longer than a year on Venus.", "answer": "True"},
    {"text": "Jupiter is the largest planet in the solar system.", "answer": "True"},
    {"text": "There are five planets between Earth and the Sun.", "answer": "False"},
    {"text": "The Moon produces its own light.", "answer": "False"},

    {"text": "The first computer bug was an actual insect.", "answer": "True"},
    {"text": "Python was named after a snake.", "answer": "False"},
    {"text": "The first website is still online.", "answer": "True"},
    {"text": "Email existed before the World Wide Web.", "answer": "True"},
    {"text": "Java and JavaScript are the same programming language.", "answer": "False"},
    {"text": "The original Xbox contained modified PC hardware.", "answer": "True"},

    {"text": "There are more stars in the universe than grains of sand on Earth.", "answer": "True"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "An avocado is a fruit.", "answer": "True"},
    {"text": "Peanuts are nuts.", "answer": "False"},
    {"text": "A tomato is legally considered a vegetable in the United States.", "answer": "True"},
    {"text": "Carrots were originally purple.", "answer": "True"},
    {"text": "The microwave oven was invented after a scientist noticed a candy bar melting in his pocket.", "answer": "True"},
    {"text": "The shortest war in history lasted less than one hour.", "answer": "True"},
    {"text": "Oxford University is older than the Aztec Empire.", "answer": "True"},
    {"text": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", "answer": "True"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Wombat poop is cube-shaped.", "answer": "True"},
    {"text": "A day on Earth is exactly 24 hours long.", "answer": "False"},
    {"text": "You cannot hum while holding your nose closed.", "answer": "True"},
    {"text": "The inventor of the Pringles can is buried in one.", "answer": "True"}
]

